### ISSUE TITLE
Error reported when using x5c certificate to decrypt signature

### ISSUE THREAD

**Issue by pengliren** [apple/app-store-server-library-java#14]
throwable:java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)

**Comment by alexanderjordanbaker** [comment]
Does this machine have internet access? Is there any more to the stack trace?

**Comment by pengliren** [comment]
> Does this machine have internet access? Is there any more to the stack trace?

The machine is located in China and connected to the network. We have tried multiple times, but this situation still occasionally occurs

**Comment by alexanderjordanbaker** [comment]
Yes, because it is reaching out to the internet to validate the certificate's revocation status. You said this only happens occasionally, correct?

**Comment by pengliren** [comment]
> Yes, because it is reaching out to the internet to validate the certificate's revocation status. You said this only happens occasionally, correct?

Yes, it happens occasionally. What are some good solutions?

**Comment by alexanderjordanbaker** [comment]
I would recommend adding some retry logic since it is possible for the network request to fail, but it sounds like it should be intermittent from your machine
